# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goarkitect < Formula
  desc "Goarkitect binary"
  homepage "https://gihub.com/omissis/goarkitect"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/omissis/goarkitect/releases/download/v0.1.0/goarkitect_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "d38ae60740bc887214ded1f5bec3c424d67b3be3bba787a20e16121ad6bf5e45"

      def install
        bin.install 'goarkitect'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/omissis/goarkitect/releases/download/v0.1.0/goarkitect_0.1.0_Darwin_arm64.tar.gz"
      sha256 "9339fd80fe4b0e84dcdc8c76e0d12e9fa649676e08ccdb19f6c37d5b2347bd02"

      def install
        bin.install 'goarkitect'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/omissis/goarkitect/releases/download/v0.1.0/goarkitect_0.1.0_Linux_arm64.tar.gz"
      sha256 "efafd6255238521e756c80b5fbb681f3b03fe435fd1d517891634cf30dc3f7d2"

      def install
        bin.install 'goarkitect'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/omissis/goarkitect/releases/download/v0.1.0/goarkitect_0.1.0_Linux_x86_64.tar.gz"
      sha256 "40c4f5e2e1f977e2d3f67ae6253dfbcd10317195de5fd11fb2ab2fd4a4bb97fa"

      def install
        bin.install 'goarkitect'
      end
    end
  end

  test do
    system "#{bin}/goarkitect"
  end
end
